spring:
  application:
    name: eureka-server

server:
  port: 9999

# Eureka 客户端配置
eureka:
  instance:
    prefer-ip-address: false
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka
  dashboard:
    path: /dashboard
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 15000
